"""Unit tests for AgentStore."""

import pytest

from identity_service.services.agent_store import AgentStore, DuplicateAgentError


@pytest.mark.unit
def test_insert_returns_agent_record(tmp_path) -> None:
    """insert() returns agent fields generated by the store."""
    store = AgentStore(db_path=str(tmp_path / "identity.db"))

    record = store.insert(name="Agent One", public_key="ed25519:aaa")

    assert set(record.keys()) == {"agent_id", "name", "public_key", "registered_at"}
    assert record["agent_id"].startswith("a-")
    assert record["name"] == "Agent One"
    assert record["public_key"] == "ed25519:aaa"
    assert record["registered_at"].endswith("Z")

    store.close()


@pytest.mark.unit
def test_get_by_id_returns_inserted_agent(tmp_path) -> None:
    """get_by_id() returns the inserted record."""
    store = AgentStore(db_path=str(tmp_path / "identity.db"))
    inserted = store.insert(name="Agent One", public_key="ed25519:aaa")

    fetched = store.get_by_id(inserted["agent_id"])

    assert fetched == inserted
    store.close()


@pytest.mark.unit
def test_get_by_id_returns_none_for_unknown_id(tmp_path) -> None:
    """get_by_id() returns None for unknown IDs."""
    store = AgentStore(db_path=str(tmp_path / "identity.db"))

    fetched = store.get_by_id("a-missing")

    assert fetched is None
    store.close()


@pytest.mark.unit
def test_list_all_returns_inserted_agents(tmp_path) -> None:
    """list_all() returns all agents without public keys."""
    store = AgentStore(db_path=str(tmp_path / "identity.db"))
    first = store.insert(name="Agent One", public_key="ed25519:aaa")
    second = store.insert(name="Agent Two", public_key="ed25519:bbb")

    listed = store.list_all()

    assert len(listed) == 2
    assert {(agent["agent_id"], agent["name"], agent["registered_at"]) for agent in listed} == {
        (first["agent_id"], first["name"], first["registered_at"]),
        (second["agent_id"], second["name"], second["registered_at"]),
    }
    store.close()


@pytest.mark.unit
def test_count_returns_total_agents(tmp_path) -> None:
    """count() returns the number of rows."""
    store = AgentStore(db_path=str(tmp_path / "identity.db"))
    store.insert(name="Agent One", public_key="ed25519:aaa")
    store.insert(name="Agent Two", public_key="ed25519:bbb")

    total = store.count()

    assert total == 2
    store.close()


@pytest.mark.unit
def test_insert_duplicate_public_key_raises(tmp_path) -> None:
    """insert() raises DuplicateAgentError for duplicate public_key."""
    store = AgentStore(db_path=str(tmp_path / "identity.db"))
    store.insert(name="Agent One", public_key="ed25519:aaa")

    with pytest.raises(DuplicateAgentError):
        store.insert(name="Agent Two", public_key="ed25519:aaa")

    store.close()


@pytest.mark.unit
def test_close_succeeds(tmp_path) -> None:
    """close() can be called without error."""
    store = AgentStore(db_path=str(tmp_path / "identity.db"))
    store.close()
