"""E2E tests for every ``/api/proxy/*`` route (T-049 test side, WP-08 item 9).

Enumerates the UI's proxy router (services/ui/src/ui_service/routers/proxy.py):
GET /api/proxy/identity, POST /api/proxy/tasks, POST
/api/proxy/tasks/{id}/bids/{id}/accept, POST /api/proxy/tasks/{id}/approve,
POST /api/proxy/tasks/{id}/dispute.

Requires the live stack (identity, bank, task-board, reputation, court, UI —
``just start-all``) and treasury provisioning (``just provision``) so the
operator account has funds to post tasks from.

Proves Q-2 (operator identity, WP-08 item 3): every proxy action is attributed
to the ``operator`` roster handle, never ``platform``. The strongest proof is
structural, not just an assertion — the Task Board only lets the *poster*
accept bids, approve, or dispute a task; since the operator posts every task
these tests create, an accept/approve/dispute call signed as platform would
be rejected with 403 (platform isn't the poster). Each test also directly
asserts the resulting ``poster_id``/``worker_id`` against both identities.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

import httpx
import pytest

from base_agent.factory import AgentFactory

if TYPE_CHECKING:
    from base_agent.agent import BaseAgent
    from base_agent.platform import PlatformAgent

pytestmark = [pytest.mark.e2e, pytest.mark.usefixtures("_require_ui_service")]

CONFIG_PATH = Path(__file__).resolve().parents[2] / "config.yaml"
UI_BASE_URL = "http://localhost:8008"


def _task_payload(title: str, reward: int = 50) -> dict[str, object]:
    return {
        "title": title,
        "spec": "Generated by WP-08 T-049 proxy-route e2e test.",
        "reward": reward,
        "bidding_deadline_seconds": 3600,
        "execution_deadline_seconds": 7200,
        "review_deadline_seconds": 3600,
    }


@pytest.fixture()
async def operator_agent_id(platform_agent: PlatformAgent) -> str:  # noqa: ARG001
    """The registered operator's agent_id, independent of the live UI process."""
    factory = AgentFactory(config_path=CONFIG_PATH)
    operator = factory.create_agent("operator")
    try:
        await operator.register()
        assert operator.agent_id is not None
        return operator.agent_id
    finally:
        await operator.close()


@pytest.fixture()
async def proxy_client():
    async with httpx.AsyncClient(base_url=UI_BASE_URL, timeout=10.0) as client:
        yield client


@pytest.fixture()
async def task_via_proxy(proxy_client: httpx.AsyncClient):
    """Post one task through the proxy; returns (task_id, poster_id)."""
    resp = await proxy_client.post("/api/proxy/tasks", json=_task_payload("Proxy lifecycle task"))
    assert resp.status_code == 200, resp.text
    body = resp.json()
    return body["task_id"], body["poster_id"]


async def _bid_and_accept_via_proxy(
    proxy_client: httpx.AsyncClient,
    make_funded_agent,
    task_id: str,
) -> BaseAgent:
    """Have a funded worker bid on task_id, accept the bid via the proxy, return the worker."""
    worker = await make_funded_agent(name="Proxy Worker", balance=0)
    bid = await worker.submit_bid(task_id=task_id, amount=10)

    resp = await proxy_client.post(f"/api/proxy/tasks/{task_id}/bids/{bid['bid_id']}/accept")
    assert resp.status_code == 200, resp.text
    return worker


# ── GET /api/proxy/identity ──────────────────────────────────────────────
async def test_proxy_identity_is_operator_not_platform(
    proxy_client: httpx.AsyncClient,
    operator_agent_id: str,
    platform_agent: PlatformAgent,
) -> None:
    resp = await proxy_client.get("/api/proxy/identity")
    assert resp.status_code == 200, resp.text

    acting_agent_id = resp.json()["agent_id"]
    assert acting_agent_id == operator_agent_id
    assert acting_agent_id != platform_agent.agent_id


# ── POST /api/proxy/tasks ────────────────────────────────────────────────
async def test_proxy_create_task_posts_as_operator_not_platform(
    proxy_client: httpx.AsyncClient,
    operator_agent_id: str,
    platform_agent: PlatformAgent,
) -> None:
    resp = await proxy_client.post("/api/proxy/tasks", json=_task_payload("Proxy create_task test"))
    assert resp.status_code == 200, resp.text
    body = resp.json()

    assert body["status"] == "open"
    assert body["poster_id"] == operator_agent_id
    assert body["poster_id"] != platform_agent.agent_id

    # Independently verify against the Task Board directly (not just the proxy's echo).
    task = await platform_agent.get_task(body["task_id"])
    assert task["poster_id"] == operator_agent_id
    assert task["poster_id"] != platform_agent.agent_id


# ── POST /api/proxy/tasks/{id}/bids/{id}/accept ──────────────────────────
async def test_proxy_accept_bid_authorized_as_operator_poster(
    proxy_client: httpx.AsyncClient,
    operator_agent_id: str,
    platform_agent: PlatformAgent,
    task_via_proxy: tuple[str, str],
    make_funded_agent,
) -> None:
    task_id, poster_id = task_via_proxy
    assert poster_id == operator_agent_id

    worker = await _bid_and_accept_via_proxy(proxy_client, make_funded_agent, task_id)
    try:
        # accept_bid on the Task Board requires the caller to BE the poster.
        # This 200 (asserted inside the helper) only happens if the proxy
        # signed as operator — the actual poster. A platform-signed request
        # would 403, since platform never posted this task.
        task = await platform_agent.get_task(task_id)
        assert task["status"] == "accepted"
        assert task["worker_id"] == worker.agent_id
        assert task["poster_id"] == operator_agent_id
        assert task["poster_id"] != platform_agent.agent_id
    finally:
        await worker.close()


# ── POST /api/proxy/tasks/{id}/approve ───────────────────────────────────
async def test_proxy_approve_task_authorized_as_operator_poster(
    proxy_client: httpx.AsyncClient,
    operator_agent_id: str,
    platform_agent: PlatformAgent,
    task_via_proxy: tuple[str, str],
    make_funded_agent,
) -> None:
    task_id, poster_id = task_via_proxy
    assert poster_id == operator_agent_id

    worker = await _bid_and_accept_via_proxy(proxy_client, make_funded_agent, task_id)
    try:
        await worker.upload_asset(task_id, "result.txt", b"Generated by WP-08 T-049 test.")
        await worker.submit_deliverable(task_id=task_id)

        balance_before = await worker.get_balance()

        resp = await proxy_client.post(f"/api/proxy/tasks/{task_id}/approve")
        assert resp.status_code == 200, resp.text

        # approve_task on the Task Board requires the caller to BE the
        # poster — the 200 above only happens signed as operator.
        task = await platform_agent.get_task(task_id)
        assert task["status"] == "approved"
        assert task["poster_id"] == operator_agent_id
        assert task["poster_id"] != platform_agent.agent_id

        balance_after = await worker.get_balance()
        assert balance_after["balance"] > balance_before["balance"]
    finally:
        await worker.close()


# ── POST /api/proxy/tasks/{id}/dispute ───────────────────────────────────
async def test_proxy_dispute_authorized_as_operator_poster(
    proxy_client: httpx.AsyncClient,
    operator_agent_id: str,
    platform_agent: PlatformAgent,
    task_via_proxy: tuple[str, str],
    make_funded_agent,
) -> None:
    task_id, poster_id = task_via_proxy
    assert poster_id == operator_agent_id

    worker = await _bid_and_accept_via_proxy(proxy_client, make_funded_agent, task_id)
    try:
        await worker.upload_asset(task_id, "result.txt", b"Generated by WP-08 T-049 test.")
        await worker.submit_deliverable(task_id=task_id)

        resp = await proxy_client.post(
            f"/api/proxy/tasks/{task_id}/dispute",
            json={"reason": "WP-08 T-049 proxy dispute test"},
        )
        assert resp.status_code == 200, resp.text

        # dispute_task on the Task Board requires the caller to BE the
        # poster — the 200 above only happens signed as operator.
        task = await platform_agent.get_task(task_id)
        assert task["status"] == "disputed"
        assert task["poster_id"] == operator_agent_id
        assert task["poster_id"] != platform_agent.agent_id
    finally:
        await worker.close()
